apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: warden-orchestrator-hpa
  namespace: warden-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: warden-orchestrator
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
